[DB Access]
DBMS=Oracle

;Oracle ================================

Url=jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=23.42.52.112)(PORT=1522)))(CONNECT_DATA=(SERVICE_NAME=OCSDB)(SERVER=DEDICATED)))

User=dahyetest
Password=acsmcs2

[TSC]
TSCID=TOCS411

[SR]
SRStart=false

[Log]
;Path=/log/TOCS
DeleteLogDay=1