#ifndef __AMC_DRIVE_H__ 
#define __AMC_DRIVE_H__ 

#define RET_EVENT_KERNEL							L"\\BaseNamedObjects\\AMC_RET_EVENT"
#define RET_EVENT_USER 							"AMC_RET_EVENT"

typedef struct __AMC_INITIALIZE_IRP
{
	ULONG	m_nIntrNum;				// [IN]
	ULONG	m_DpramPhyAddr;			// [IN]
	char*	m_pDpramVirAddr;	// [OUT]
}AMC_INITIALIZE_IRP;

typedef struct __AMC_REGSRW_IRP
{
	ULONG	m_nOffset;
	ULONG	m_nData;
	ULONG	m_bSuccess;
}AMC_REGSRW_IRP;

typedef struct __AMC_REGSRWGRP_IRP
{
	ULONG	m_nOffset;
	ULONG	m_nCount;
	ULONG	m_bSuccess;
	unsigned char m_arrData[1024];
}AMC_REGSRWGRP_IRP;

#define IOCTL_INIT_AMCDRV						CTL_CODE(FILE_DEVICE_UNKNOWN, 0x800, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_RELEASE_AMCDRV					CTL_CODE(FILE_DEVICE_UNKNOWN, 0x801, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_READ_BUFREG						CTL_CODE(FILE_DEVICE_UNKNOWN, 0x810, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_WRITE_BUFREG						CTL_CODE(FILE_DEVICE_UNKNOWN, 0x811, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_READ_BUFREGS						CTL_CODE(FILE_DEVICE_UNKNOWN, 0x812, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_WRITE_BUFREGS						CTL_CODE(FILE_DEVICE_UNKNOWN, 0x813, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_COMMAND							CTL_CODE(FILE_DEVICE_UNKNOWN, 0x811, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_GET_DBGINFO						CTL_CODE(FILE_DEVICE_UNKNOWN, 0x8FF, METHOD_BUFFERED, FILE_ANY_ACCESS)

#endif
