[BOOTPARAM_BD_0]

[AXIS_1]
VEL_LIMIT = 2047000.000000
ACC_LIMIT = 500.000000
PULSE_RATIO = 8.000000
GEAR_RATIO = 1.000000
HWLOWER_LIMIT = -2147483648.000000
HWUPPER_LIMIT = 2147483647.000000
SWLOWER_LIMIT = -2147483648.000000
SWUPPER_LIMIT = 2147483647.000000
PGAIN = 12000.000000
IGAIN = 0.000000
DGAIN = 0.000000
FGAIN = 0.000000
ILIMIT = 1000.000000
VPGAIN = 0.000000
VIGAIN = 0.000000
VDGAIN = 0.000000
VFGAIN = 0.000000
VILIMIT = 1000.000000
IN_POSITION = 100.000000
ERROR_LIMIT = 35000.000000

# 0:servo, 1:stepper, 2:micro-stepper
MOTOR_TYPE = 0

SWUPPER_LIMITST = 0
SWLOWER_LIMITST = 0
POS_LEVEL = 0
NEG_LEVEL = 0
HOME_LEVEL = 0
AMP_LEVEL = 1
AMP_RESET_LEVEL = 0
POS_LEVEL_ST = 3
NEG_LEVEL_ST = 3
HOME_LEVEL_ST = 3
AMP_LEVEL_ST = 0

# always 0: encoder
ENCODER_CFG = 0

# 0:bipolar, 1:unipolar
VOLTAGE_CFG = 0
HOME_INDEX = 0
STOP_RATE = 10
ESTOP_RATE = 25

# 0:velocity, 1:torque
CONTROL_CFG = 0

# 0:open, 1:closed loop
LOOP_CFG = 0

AMP_ON_LEVEL = 0
IO_INT_ENABLE = 0.000000
INT_EVENT_ST = 0
AMP_FAULT_EVENT = 0

# 0:only_standing, 1:always
POS_IMODE = 1
# 0:only_standing, 1:always
VEL_IMODE = 1

PULSE_MODE = 0
INPOS_LEVEL = 0.000000
#DPRAM_ADDR = 0.000000
#AXIS_NUM = 0
#ACTION_AXIS_NUM = 0
# NOT USED ON this AMC. 0:input, 1:output
USERIO_BOOTMODE = 0
# initial user output value only for lower 32bits
USERIO_BOOTVALUE = 0
#DAC_BIAS = 0.000000
VTRACKING_FACTOR = 1.000000
ENCODER_OFFSET = 0.000000

# CW=0, CCW=1
ENCODER_DIR = 1
MOTOR_PAUSE = 0
MOTOR_PAUSE_LEVEL = 1
MOTOR_PAUSE_CHECKBIT = 0





[AXIS_2]
VEL_LIMIT = 2047000.000000
ACC_LIMIT = 500.000000
PULSE_RATIO = 8.000000
GEAR_RATIO = 1.000000
HWLOWER_LIMIT = -2147483648.000000
HWUPPER_LIMIT = 2147483647.000000
SWLOWER_LIMIT = -2147483648.000000
SWUPPER_LIMIT = 2147483647.000000
PGAIN = 12000.000000
IGAIN = 0.000000
DGAIN = 0.000000
FGAIN = 0.000000
ILIMIT = 1000.000000
VPGAIN = 0.000000
VIGAIN = 0.000000
VDGAIN = 0.000000
VFGAIN = 0.000000
VILIMIT = 1000.000000
IN_POSITION = 100.000000
ERROR_LIMIT = 35000.000000
MOTOR_TYPE = 0
SWUPPER_LIMITST = 0
SWLOWER_LIMITST = 0
POS_LEVEL = 0
NEG_LEVEL = 0
HOME_LEVEL = 0
AMP_LEVEL = 1
AMP_RESET_LEVEL = 0
POS_LEVEL_ST = 3
NEG_LEVEL_ST = 3
HOME_LEVEL_ST = 3
AMP_LEVEL_ST = 0
ENCODER_CFG = 0
VOLTAGE_CFG = 0
HOME_INDEX = 0
STOP_RATE = 10
ESTOP_RATE = 25
CONTROL_CFG = 0
LOOP_CFG = 0
AMP_ON_LEVEL = 0
IO_INT_ENABLE = 0.000000
INT_EVENT_ST = 0
AMP_FAULT_EVENT = 0
POS_IMODE = 1
VEL_IMODE = 1
PULSE_MODE = 0
INPOS_LEVEL = 0.000000
#DPRAM_ADDR = 0.000000
#AXIS_NUM = 0
#ACTION_AXIS_NUM = 0
USERIO_BOOTMODE = 0
USERIO_BOOTVALUE = 0
#DAC_BIAS = 0.000000
VTRACKING_FACTOR = 1.000000
ENCODER_OFFSET = 0.000000
ENCODER_DIR = 1
MOTOR_PAUSE = 0
MOTOR_PAUSE_LEVEL = 1
MOTOR_PAUSE_CHECKBIT = 0

[AXIS_3]
VEL_LIMIT = 2047000.000000
ACC_LIMIT = 500.000000
PULSE_RATIO = 8.000000
GEAR_RATIO = 1.000000
HWLOWER_LIMIT = -2147483648.000000
HWUPPER_LIMIT = 2147483647.000000
SWLOWER_LIMIT = -2147483648.000000
SWUPPER_LIMIT = 2147483647.000000
PGAIN = 1200.000000
IGAIN = 20.000000
DGAIN = 0.000000
FGAIN = 0.000000
ILIMIT = 1000.000000
VPGAIN = 1000.000000
VIGAIN = 10.000000
VDGAIN = 0.000000
VFGAIN = 0.000000
VILIMIT = 3276800.000000
IN_POSITION = 100.000000
ERROR_LIMIT = 35000.000000
MOTOR_TYPE = 0
SWUPPER_LIMITST = 0
SWLOWER_LIMITST = 0
POS_LEVEL = 0
NEG_LEVEL = 0
HOME_LEVEL = 0
AMP_LEVEL = 1
AMP_RESET_LEVEL = 0
POS_LEVEL_ST = 3
NEG_LEVEL_ST = 3
HOME_LEVEL_ST = 3
AMP_LEVEL_ST = 0
ENCODER_CFG = 0
VOLTAGE_CFG = 0
HOME_INDEX = 0
STOP_RATE = 10
ESTOP_RATE = 25
CONTROL_CFG = 0
LOOP_CFG = 0
AMP_ON_LEVEL = 0
IO_INT_ENABLE = 0.000000
INT_EVENT_ST = 0
AMP_FAULT_EVENT = 0
POS_IMODE = 1
VEL_IMODE = 1
PULSE_MODE = 0
INPOS_LEVEL = 0.000000
#DPRAM_ADDR = 0.000000
#AXIS_NUM = 0
#ACTION_AXIS_NUM = 0
USERIO_BOOTMODE = 0
USERIO_BOOTVALUE = 0
#DAC_BIAS = 0.000000
VTRACKING_FACTOR = 1.000000
ENCODER_OFFSET = 0.000000
ENCODER_DIR = 1
MOTOR_PAUSE = 0
MOTOR_PAUSE_LEVEL = 1
MOTOR_PAUSE_CHECKBIT = 0

[AXIS_4]
VEL_LIMIT = 2047000.000000
ACC_LIMIT = 500.000000
PULSE_RATIO = 8.000000
GEAR_RATIO = 1.000000
HWLOWER_LIMIT = -2147483648.000000
HWUPPER_LIMIT = 2147483647.000000
SWLOWER_LIMIT = -2147483648.000000
SWUPPER_LIMIT = 2147483647.000000
PGAIN = 1200.000000
IGAIN = 20.000000
DGAIN = 0.000000
FGAIN = 0.000000
ILIMIT = 1000.000000
VPGAIN = 1000.000000
VIGAIN = 10.000000
VDGAIN = 0.000000
VFGAIN = 0.000000
VILIMIT = 3276800.000000
IN_POSITION = 100.000000
ERROR_LIMIT = 35000.000000
MOTOR_TYPE = 0
SWUPPER_LIMITST = 0
SWLOWER_LIMITST = 0
POS_LEVEL = 0
NEG_LEVEL = 0
HOME_LEVEL = 0
AMP_LEVEL = 1
AMP_RESET_LEVEL = 0
POS_LEVEL_ST = 3
NEG_LEVEL_ST = 3
HOME_LEVEL_ST = 3
AMP_LEVEL_ST = 0
ENCODER_CFG = 0
VOLTAGE_CFG = 0
HOME_INDEX = 0
STOP_RATE = 10
ESTOP_RATE = 25
CONTROL_CFG = 0
LOOP_CFG = 0
AMP_ON_LEVEL = 0
IO_INT_ENABLE = 0.000000
INT_EVENT_ST = 0
AMP_FAULT_EVENT = 0
POS_IMODE = 1
VEL_IMODE = 1
PULSE_MODE = 0
INPOS_LEVEL = 0.000000
#DPRAM_ADDR = 0.000000
#AXIS_NUM = 0
#ACTION_AXIS_NUM = 0
USERIO_BOOTMODE = 0
USERIO_BOOTVALUE = 0
#DAC_BIAS = 0.000000
VTRACKING_FACTOR = 1.000000
ENCODER_OFFSET = 0.000000
ENCODER_DIR = 1
MOTOR_PAUSE = 0
MOTOR_PAUSE_LEVEL = 1
MOTOR_PAUSE_CHECKBIT = 0
