[DB Access]
DBMS=Oracle

;Oracle ================================
Url=jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=23.42.52.112)(PORT=1522)))(CONNECT_DATA=(SERVICE_NAME=OCSDB)(SERVER=DEDICATED)))
User=mig_s1ph24f
Password=acsmcs2
DeleteDBHistoryDay=7
HostServiceType=Primary

[UCInterface]
DGR_MAXVHL_LIMIT=15
UCInterfacePort=4050
UCInterfaceTCPPort=4100
MAX_CLIENT=2

[Log]
Path=./log
DeleteLogDay=1
